
##  ##  ####  ##  ##  ##     #### #####  ##### ##  ##
##  ## ##  ## ##  ##  ##    ## ## ##  ## ## ## ##  ##
###### ##  ## ##   ####    ##  ## ###### ##    ######
##  ## ##  ## ##    ##     ###### ## ##  ## ## ##  ##
##  ##  ####  ####  ##     ##  ## ##  ## ##### ##  ##


################
### MONITORS ###
################

source = ~/.config/hypr/Monitors.conf


###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/Programs.conf


#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/EnvironmentVariables.conf


###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/Permissions.conf


######################
### GENERAL DESIGN ###
######################

source = ~/.config/hypr/GeneralDesign.conf


###############
### LAYOUTS ###
###############

source = ~/.config/hypr/Layouts.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/Input.conf


###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/KeyBindings.conf


###############
### WINDOWS ###
###############

source = ~/.config/hypr/Windows.conf


##################
### WORKSPACES ###
##################

source = ~/.config/hypr/Workspaces.conf
