#############
### INPUT ###
#############


input {
    kb_layout = us,ua
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}


gesture = 3, horizontal, workspace


device {
    name = sino-wealth-trust-redex-v2-wireless
    sensitivity = -1.0
}
